version: '3.9'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: go
    container_name: go
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    env_file:
      - ./.env